export const COMMENT_POST_REQUEST = 'COMMENT_POST_REQUEST';
export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS';
export const COMMENT_POST_FAIL = 'COMMENT_POST_FAIL';

export const COMMENT_GET_REQUEST = 'COMMENT_GET_REQUEST';
export const COMMENT_GET_SUCCESS = 'COMMENT_GET_SUCCESS';
export const COMMENT_GET_FAIL = 'COMMENT_GET_FAIL';

export const USER_LIKE_REQUEST = 'USER_LIKE_REQUEST';
export const USER_LIKE_SUCCESS= 'USER_LIKE_SUCCESS';
export const USER_LIKE_FAIL = 'USER_LIKE_FAIL';

export const NUMBER_LIKE_MOTO_REQUEST = 'NUMBER_LIKE_MOTO_REQUEST';
export const NUMBER_LIKE__MOTO_SUCCESS= 'NUMBER_LIKE__MOTO_SUCCESS';
export const NUMBER_LIKE_MOTO_FAIL = 'NUMBER_LIKE_MOTO_FAIL';

export const PUSH_USER_LIKE_MOTO_REQUEST = 'PUSH_USER_LIKE_MOTO_REQUEST';
export const PUSH_USER_LIKE__MOTO_SUCCESS= 'PUSH_USER_LIKE__MOTO_SUCCESS';
export const PUSH_USER_LIKE_MOTO_FAIL = 'PUSH_USER_LIKE_MOTO_FAIL';