export const COMMENT_REVIEW_POST_REQUEST = 'COMMENT_REVIEW_POST_REQUEST';
export const COMMENT_REVIEW_POST_SUCCESS = 'COMMENT_REVIEW_POST_SUCCESS';
export const COMMENT_REVIEW_POST_FAIL = 'COMMENT_REVIEW_POST_FAIL';

export const COMMENT_REVIEW_GET_REQUEST = 'COMMENT_REVIEW_GET_REQUEST';
export const COMMENT_REVIEW_GET_SUCCESS = 'COMMENT_REVIEW_GET_SUCCESS';
export const COMMENT_REVIEW_GET_FAIL = 'COMMENT_REVIEW_GET_FAIL';

export const USER_LIKE_REVIEW_REQUEST = 'USER_LIKE_REVIEW_REQUEST';
export const USER_LIKE_REVIEW_SUCCESS= 'USER_LIKE_REVIEW_SUCCESS';
export const USER_LIKE_REVIEW_FAIL = 'USER_LIKE_REVIEW_FAIL';

export const NUMBER_LIKE_REVIEW_REQUEST = 'NUMBER_LIKE_REVIEW_REQUEST';
export const NUMBER_LIKE_REVIEW_SUCCESS= 'NUMBER_LIKE_REVIEW_SUCCESS';
export const NUMBER_LIKE_REVIEW_FAIL = 'NUMBER_LIKE_REVIEW_FAIL';

export const PUSH_USER_LIKE_REVIEW_REQUEST = 'PUSH_USER_LIKE_REVIEW_REQUEST';
export const PUSH_USER_LIKE_REVIEW_SUCCESS= 'PUSH_USER_LIKE__REVIEW_SUCCESS';
export const PUSH_USER_LIKE_REVIEW_FAIL = 'PUSH_USER_LIKE_REVIEW_FAIL';