export const COMMENT_FORUM_POST_REQUEST = 'COMMENT_FORUM_POST_REQUEST';
export const COMMENT_FORUM_POST_SUCCESS = 'COMMENT_FORUM_POST_SUCCESS';
export const COMMENT_FORUM_POST_FAIL = 'COMMENT_FORUM_POST_FAIL';

export const COMMENT_FORUM_GET_REQUEST = 'COMMENT_FORUM_GET_REQUEST';
export const COMMENT_FORUM_GET_SUCCESS = 'COMMENT_FORUM_GET_SUCCESS';
export const COMMENT_FORUM_GET_FAIL = 'COMMENT_FORUM_GET_FAIL';

export const GET_USER_LIKE_COMMENT_FORUM_REQUEST = 'GET_USER_LIKE_COMMENT_FORUM_REQUEST';
export const GET_USER_LIKE_COMMENT_FORUM_SUCCESS= 'GET_USER_LIKE_COMMENT_FORUM_SUCCESS';
export const GET_USER_LIKE_COMMENT_FORUM_FAIL = 'GET_USER_LIKE_COMMENT_FORUM_FAIL';

export const PUT_LIKE_COMMENT_FORUM_REQUEST = 'PUT_LIKE_COMMENT_FORUM_REQUEST';
export const PUT_LIKE_COMMENT_FORUM_SUCCESS= 'PUT_LIKE_COMMENT_FORUM_SUCCESS';
export const PUT_LIKE_COMMENT_FORUM_FAIL = 'PUT_LIKE_COMMENT_FORUM_FAIL';

export const PUSH_USER_LIKE_COMMENT_FORUM_REQUEST = 'PUSH_USER_LIKE_COMMENT_FORUM_REQUEST';
export const PUSH_USER_LIKE_COMMENT_FORUM_SUCCESS= 'PUSH_USER_LIKE_COMMENT_FORUM_SUCCESS';
export const PUSH_USER_LIKE_COMMENT_FORUM_FAIL = 'PUSH_USER_LIKE_COMMENT_FORUM_FAIL';