export const COMMENT_FOOD_POST_REQUEST = 'COMMENT_FOOD_POST_REQUEST';
export const COMMENT_FOOD_POST_SUCCESS = 'COMMENT_FOOD_POST_SUCCESS';
export const COMMENT_FOOD_POST_FAIL = 'COMMENT_FOOD_POST_FAIL';

export const COMMENT_FOOD_GET_REQUEST = 'COMMENT_FOOD_GET_REQUEST';
export const COMMENT_FOOD_GET_SUCCESS = 'COMMENT_FOOD_GET_SUCCESS';
export const COMMENT_FOOD_GET_FAIL = 'COMMENT_FOOD_GET_FAIL';

export const USER_LIKE_FOOD_REQUEST = 'USER_LIKE_FOOD_REQUEST';
export const USER_LIKE_FOOD_SUCCESS= 'USER_LIKE_FOOD_SUCCESS';
export const USER_LIKE_FOOD_FAIL = 'USER_LIKE_FOOD_FAIL';

export const NUMBER_LIKE_FOOD_REQUEST = 'NUMBER_LIKE_FOOD_REQUEST';
export const NUMBER_LIKE_FOOD_SUCCESS= 'NUMBER_LIKE_FOOD_SUCCESS';
export const NUMBER_LIKE_FOOD_FAIL = 'NUMBER_LIKE_FOOD_FAIL';

export const PUSH_USER_LIKE_FOOD_REQUEST = 'PUSH_USER_LIKE_FOOD_REQUEST';
export const PUSH_USER_LIKE__FOOD_SUCCESS= 'PUSH_USER_LIKE__FOOD_SUCCESS';
export const PUSH_USER_LIKE_FOOD_FAIL = 'PUSH_USER_LIKE_FOOD_FAIL';