export const FILTER_MOTO_REQUEST= 'FILTER_MOTO_REQUEST';
export const FILTER_MOTO_GIA_SUCCESS = 'FILTER_MOTO_GIA_SUCCESS';
export const FILTER_MOTO_BRAND_SUCCESS = 'FILTER_MOTO_BRAND_SUCCESS';
export const FILTER_MOTO_NOTALL_SUCCESS = 'FILTER_MOTO_NOTALL_SUCCESS';
export const FILTER_MOTO_ALL_SUCCESS = 'FILTER_MOTO_ALL_SUCCESS';
export const FILTER_MOTO_FAIL = 'FILTER_MOTO_FAIL';

export const FILTER_FOOD_REQUEST= 'FILTER_FOOD_REQUEST';
export const FILTER_FOOD_GIA_SUCCESS = 'FILTER_FOOD_GIA_SUCCESS';
export const FILTER_FOOD_RATING_SUCCESS = 'FILTER_FOOD_RATING_SUCCESS';
export const FILTER_FOOD_NOTALL_SUCCESS = 'FILTER_FOOD_NOTALL_SUCCESS';
export const FILTER_FOOD_ALL_SUCCESS = 'FILTER_FOOD_ALL_SUCCESS';
export const FILTER_FOOD_FAIL = 'FILTER_FOOD_FAIL';


export const SEARCH_MOTO_ALL_REQUEST = 'SEARCH_MOTO_ALL_REQUEST';
export const SEARCH_MOTO_ALL_SUCCESS = 'SEARCH_MOTO_ALL_SUCCESS';
export const SEARCH_MOTO_ALL_FAIL = 'SEARCH_MOTO_ALL_FAIL';