export const FOOD_REVIEW_REQUEST = 'FOOD_REVIEW_REQUEST';
export const FOOD_REVIEW_SUCCESS = 'FOOD_REVIEW_SUCCESS';
export const FOOD_REVIEW_FAIL = 'FOOD_REVIEW_FAIL';

export const FOOD_REVIEW_DETAIL_REQUEST = 'FOOD_REVIEW_DETAIL_REQUEST';
export const FOOD_REVIEW_DETAIL_SUCCESS = 'FOOD_REVIEW_DETAIL_SUCCESS';
export const FOOD_REVIEW_DETAIL_FAIL = 'FOOD_REVIEW_DETAIL_FAIL';

export const FOOD_REVIEW_MENU_REQUEST = 'FOOD_REVIEW_MENU_REQUEST';
export const FOOD_REVIEW_MENU_SUCCESS = 'FOOD_REVIEW_MENU_SUCCESS';
export const FOOD_REVIEW_MENU_FAIL = 'FOOD_REVIEW_MENU_FAIL';

export const FOOD_REVIEW_BY_CB_REQUEST = 'FOOD_REVIEW_BY_CB_REQUEST';
export const FOOD_REVIEW_BY_CB_SUCCESS = 'FOOD_REVIEW_BY_CB_SUCCESS';
export const FOOD_REVIEW_BY_CB_FAIL = 'FOOD_REVIEW_BY_CB_FAIL';

// export const FOOD_REVIEW_BY_NAME_REQUEST = 'FOOD_REVIEW_BY_NAME_REQUEST';
// export const FOOD_REVIEW_BY_NAME_SUCCESS = 'FOOD_REVIEW_BY_NAME_SUCCESS';
// export const FOOD_REVIEW_BY_NAME_FAIL = 'FOOD_REVIEW_BY_NAME_FAIL';