export const FORUM_GET_BY_CITY_REQUEST = 'FORUM_GET_BY_CITY_REQUEST';
export const FORUM_GET_BY_CITY_SUCCESS = 'FORUM_GET_BY_CITY_SUCCESS';
export const FORUM_GET_BY_CITY_FAIL = 'FORUM_GET_BY_CITY_FAIL';

export const FORUM_GET_BY_ID_REQUEST = 'FORUM_GET_BY_ID_REQUEST';
export const FORUM_GET_BY_ID_SUCCESS = 'FORUM_GET_BY_ID_SUCCESS';
export const FORUM_GET_BY_ID_FAIL = 'FORUM_GET_BY_ID_FAIL';

export const FORUM_GET_BY_NAME_REQUEST = 'FORUM_GET_BY_NAME_REQUEST';
export const FORUM_GET_BY_NAME_SUCCESS = 'FORUM_GET_BY_NAME_SUCCESS';
export const FORUM_GET_BY_NAME_FAIL = 'FORUM_GET_BY_NAME_FAIL';

export const FORUM_GET_BY_BRAND_AND_PALCE_REQUEST = 'FORUM_GET_BY_BRAND_AND_PALCE_REQUEST';
export const FORUM_GET_BY_BRAND_AND_PALCE_SUCCESS = 'FORUM_GET_BY_BRAND_AND_PALCE_SUCCESS';
export const FORUM_GET_BY_BRAND_AND_PALCE_FAIL = 'FORUM_GET_BY_BRAND_AND_PALCE_FAIL';

export const FORUM_POST_BY_BRAND_AND_PALCE_REQUEST = 'FORUM_POST_BY_BRAND_AND_PALCE_REQUEST';
export const FORUM_POST_BY_BRAND_AND_PALCE_SUCCESS = 'FORUM_POST_BY_BRAND_AND_PALCE_SUCCESS';
export const FORUM_POST_BY_BRAND_AND_PALCE_FAIL = 'FORUM_POST_BY_BRAND_AND_PALCE_FAIL';

export const FORUM_PUT_LIKE_REQUEST = 'FORUM_PUT_LIKE_REQUEST';
export const FORUM_PUT_LIKE_SUCCESS = 'FORUM_PUT_LIKE_SUCCESS';
export const FORUM_PUT_LIKE_FAIL = 'FORUM_PUT_LIKE_FAIL';

export const FORUM_GET_USER_LIKE_REQUEST = 'FORUM_GET_USER_LIKE_REQUEST';
export const FORUM_GET_USER_LIKE_SUCCESS = 'FORUM_GET_USER_LIKE_SUCCESS';
export const FORUM_GET_USER_LIKE_FAIL = 'FORUM_GET_USER_LIKE_FAIL';

export const FORUM_POST_USER_LIKE_REQUEST = 'FORUM_POST_USER_LIKE_REQUEST';
export const FORUM_POST_USER_LIKE_SUCCESS = 'FORUM_POST_USER_LIKE_SUCCESS';
export const FORUM_POST_USER_LIKE_FAIL = 'FORUM_POST_USER_LIKE_FAIL';

