export const NOTE_POST_TODOLISTS_REQUEST = 'NOTE_POST_TODOLISTS_REQUEST';
export const NOTE_POST_TODOLISTS_SUCCESS = 'NOTE_POST_TODOLISTS_SUCCESS';
export const NOTE_POST_TODOLISTS_FAIL = 'NOTE_POST_TODOLISTS_FAIL';

export const NOTE_GET_TODOLISTS_REQUEST = 'NOTE_GET_TODOLISTS_REQUEST';
export const NOTE_GET_TODOLISTS_SUCCESS = 'NOTE_GET_TODOLISTS_SUCCESS';
export const NOTE_GET_TODOLISTS_FAIL = 'NOTE_GET_TODOLISTS_FAIL';

export const NOTE_POST_DATA_TODOLIST_REQUEST = 'NOTE_POST_DATA_TODOLIST_REQUEST';
export const NOTE_POST_DATA_TODOLIST_SUCCESS = 'NOTE_POST_DATA_TODOLIST_SUCCESS';
export const NOTE_POST_DATA_TODOLIST_FAIL = 'NOTE_POST_DATA_TODOLIST_FAIL';

export const NOTE_GET_DATA_TODOLIST_REQUEST = 'NOTE_GET_DATA_TODOLIST_REQUEST';
export const NOTE_GET_DATA_TODOLIST_SUCCESS = 'NOTE_GET_DATA_TODOLIST_SUCCESS';
export const NOTE_GET_DATA_TODOLIST_FAIL = 'NOTE_GET_DATA_TODOLIST_REQUEST';

export const NOTE_PUT_DATA_TODOLIST_REQUEST = 'NOTE_PUT_DATA_TODOLIST_REQUEST';
export const NOTE_PUT_DATA_TODOLIST_SUCCESS = 'NOTE_PUT_DATA_TODOLIST_SUCCESS';
export const NOTE_PUT_DATA_TODOLIST_FAIL = 'NOTE_PUT_DATA_TODOLIST_FAIL';

export const NOTE_DELETE_DATA_TODOLIST_REQUEST = 'NOTE_DELETE_DATA_TODOLIST_REQUEST';
export const NOTE_DELETE_DATA_TODOLIST_SUCCESS = 'NOTE_DELETE_DATA_TODOLIST_SUCCESS';
export const NOTE_DELETE_DATA_TODOLIST_FAIL = 'NOTE_DELETE_DATA_TODOLIST_FAIL';

export const NOTE_GET_DATA_TODOLIST_ID_REQUEST = 'NOTE_GET_DATA_TODOLIST_ID_REQUEST';
export const NOTE_GET_DATA_TODOLIST_ID_SUCCESS = 'NOTE_GET_DATA_TODOLIST_ID_SUCCESS';
export const NOTE_GET_DATA_TODOLIST_ID_FAIL = 'NOTE_GET_DATA_TODOLIST_ID_FAIL';