export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_TOTALROW_REQUEST= 'PRODUCT_TOTALROW_REQUEST';
export const PRODUCT_TOTALROW_SUCCESS = 'PRODUCT_TOTALROW_SUCCESS';
export const PRODUCT_TOTALROW_FAIL = 'PRODUCT_TOTALROW_FAIL';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';