export const REVIEW_DLTC_REQUEST = 'REVIEW_DLTC_REQUEST';
export const REVIEW_DLTC_SUCCESS = 'REVIEW_DLTC_SUCCESS';
export const REVIEW_DLTC_FAIL = 'REVIEW_DLTC_FAIL';

export const REVIEW_DTLS_REQUEST = 'REVIEW_DTLS_REQUEST';
export const REVIEW_DTLS_SUCCESS = 'REVIEW_DTLS_SUCCESS';
export const REVIEW_DTLS_FAIL = 'REVIEW_DTLS_FAIL';

export const REVIEW_LISTDETAIL_REQUEST = 'REVIEW_LISTDETAIL_REQUEST';
export const REVIEW_LISTDETAIL_SUCCESS = 'REVIEW_LISTDETAIL_SUCCESS';
export const REVIEW_LISTDETAIL_FAIL = 'REVIEW_LISTDETAIL_FAIL';