export const REVIEW_DETAIL_1_REQUEST = 'REVIEW_DETAIL_1_REQUEST';
export const REVIEW_DETAIL_1_SUCCESS = 'REVIEW_DETAIL_1_SUCCESS';
export const REVIEW_DETAIL_1_FAIL = 'REVIEW_DETAIL_1_FAIL';

export const REVIEW_DETAIL_2_REQUEST = 'REVIEW_DETAIL_2_REQUEST';
export const REVIEW_DETAIL_2_SUCCESS = 'REVIEW_DETAIL_2_SUCCESS';
export const REVIEW_DETAIL_2_FAIL = 'REVIEW_DETAIL_2_FAIL';